### ISSUE TITLE
IP address for Ingress with Traefik

### ISSUE THREAD

**Issue by echarles** [datalayer/helm-charts#25]
The ingress created by traefik do not show IP address, this can be tricky if an External DNS system is used to automatically create the DNS entry.

```
NAMESPACE            NAME                                         CLASS               HOSTS               ADDRESS   PORTS     AGE
datalayer-api        iam-ingress                                  datalayer-traefik   oss.datalayer.run             80, 443   32h
datalayer-api        jupyter-ingress                              datalayer-traefik   oss.datalayer.run             80, 443   32h
datalayer-api        jupyter-server-ingress                       datalayer-traefik   oss.datalayer.run             80, 443   53d
datalayer-api        library-ingress                              datalayer-traefik   oss.datalayer.run             80, 443   32h
datalayer-api        spacer-ingress                               datalayer-traefik   oss.datalayer.run             80, 443   32h
```

@tyu0912 has come with a fix for that. We should enroll that fix.

```yaml
kubernetesIngress:
  ingressClass: "datalayer-traefik"
  ingressEndpoint:
    publishedService: "datalayer-traefik/datalayer-traefik"
```
