### ISSUE TITLE
Support `cephable` node roles

### ISSUE THREAD

**Issue by echarles** [datalayer/helm-charts#53]
Ensure the needed drives for ceph are installed on the correct nodes that need them (not only the ceph nodes, but also the nodes that need to mount them.

This section in the ceph operator (aka rook operator) helm chart needs to be tuned to implement that requirement.

```yaml
  # -- Array of tolerations in YAML format which will be added to CSI provisioner deployment
  provisionerTolerations:
  #    - key: key
  #      operator: Exists
  #      effect: NoSchedule

  # -- The node labels for affinity of the CSI provisioner deployment [^1]
  provisionerNodeAffinity: role.datalayer.io/ceph=true #key1=value1,value2; key2=value3
  # Set pluginTolerations and pluginNodeAffinity for plugin daemonset pods.
  # The CSI plugins need to be started on all the nodes where the clients need to mount the storage.

  # -- Array of tolerations in YAML format which will be added to CephCSI plugin DaemonSet
  pluginTolerations:
  #    - key: key
  #      operator: Exists
  #      effect: NoSchedule

  # -- The node labels for affinity of the CephCSI RBD plugin DaemonSet [^1]
  pluginNodeAffinity: role.datalayer.io/jupyter=true # key1=value1,value2; key2=value3
```
